#!/usr/bin/python

for letter in 'Python':     # First Example
   print 'Current Letter :', letter

fruits = ['banana', 'apple',  'Guva']
Hello
for fruit in fruits:        # Second Example
   print 'Current fruit :', fruit

print "Good bye!"
