#!/usr/bin/python

for letter in 'Python':     # First Example
   print 'Current Letter :', letter

fruits = ['banana', 'Grapes',  'mango']
print "siva"
for fruit in fruits:        # Second Example
   print 'Current fruit :', apple

print "Good bye!"
